[supervisord]

nodaemon=true



[program:mysql]

command=/usr/bin/mysqld_safe --datadir=/var/lib/mysql

autostart=true

autorestart=true

stdout_logfile=/dev/stdout

stderr_logfile=/dev/stderr



[program:apache]

command=/usr/sbin/apache2ctl -D FOREGROUND

autostart=true

autorestart=true

stdout_logfile=/dev/stdout

stderr_logfile=/dev/stderr